---
- name: install jenkins
  hosts: localhost
  become: yes
  become_user: root

  tasks:
  - name: apt update 
    apt:
      name: "*"
      state: prasent

  - name: download jenkins key
    ansible.builtin.get_url:
      url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
      dest: /usr/share/keyrings/jenkins-keyring.asc

  - name: Add jenkins repo
    ansible.builtin.apt_repository:
      repo: [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \https://pkg.jenkins.io/debian binary/
      state: present
      filename: jenkins.list

  - name: apt update
    apt:
      name: "*"
      state: latest

  - name: install java
    apt:
      name: openjdk-11-jre
      state: latest

  - name: install jenkins
    apt:
      name: jenkins
      state: latest

  - name: start jenkins
    ansible.builtin.service:
      name: jenkins
      state: started

